### ISSUE TITLE
A slightly better way to overclock and tweak your Nvidia GPU

### ISSUE THREAD

**Issue by Xayneex** [djdallmann/GamingPCSetup#10]
https://docs.google.com/document/d/14ma-_Os3rNzio85yBemD-YSpF_1z75mZJz1UdzmW8GE/edit

**Comment by djdallmann** [comment]
Cancerogeno's guide right?

**Comment by Xayneex** [comment]
Bro, I would really like to learn more different articles and information in the field of tweaking. Can you please help me, send me some information (links, articles)about this

**Comment by Xayneex** [comment]
I will be very grateful

**Comment by djdallmann** [comment]
Thanks for the feedback.
