### ISSUE TITLE
Affinity of CRSS  keep changing after restarting pc

### ISSUE THREAD

**Issue by sslide** [djdallmann/GamingPCSetup#11]
Hi
I appreciate your guide very much. 
This is just a minor inconvenience that is bugging me while I troubleshoot. 
Only fix on I found online is process lasso and I don't want to use it. 
Is there a way to permanently set it with process hacker?
  Your feedback is appreciated. Thanks

**Comment by Zusier** [comment]
You can save affinities/priorities within Process Hacker (in [nightly builds](https://processhacker.sourceforge.io/nightly.php), not 2.x)

**Comment by spddl** [comment]
or set CSRSS per IFEO:
```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\csrss.exe]

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\csrss.exe\PerfOptions]
"CpuPriorityClass"=dword:00000003
```

and DWM as task:
```xml
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Date>2021-11-16T21:12:25</Date>
    <Author>spddl</Author>
    <URI>\SetDwmToLow</URI>
  </RegistrationInfo>
  <Triggers>
    <LogonTrigger>
      <StartBoundary>2021-11-16T21:12:00</StartBoundary>
      <Enabled>true</Enabled>
    </LogonTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>S-1-5-18</UserId>
      <RunLevel>HighestAvailable</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>true</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>true</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>false</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <Duration>PT10M</Duration>
      <WaitTimeout>PT1H</WaitTimeout>
      <StopOnIdleEnd>true</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT72H</ExecutionTimeLimit>
    <Priority>7</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>wmic</Command>
      <Arguments>process where name="dwm.exe" call setpriority 64</Arguments>
    </Exec>
  </Actions>
</Task>
```

**Comment by sslide** [comment]
Thank you all

**Comment by djdallmann** [comment]
Thanks for jumping in @Zusier @spddl

**Comment by sslide** [comment]
I can save affinity and priority of DWM. However, I can only save the priority for CRSS. It's Affinity keeps defaulting after I restart my pc. I'm running out of thoughts.

**Comment by djdallmann** [comment]
CSRSS is a critical windows process so tools like ProcessLasso if I recall (correct me if I'm wrong) don't run at the same privilege level and isn't able to modify the affinities etc.

You could setup a simple login script to use processhacker to make the changes then have the script also unload processhacker dll at the end once the change is made since it's detected as unwanted dll by some anti-cheats.

**Comment by sslide** [comment]
> CSRSS is a critical windows process so tools like ProcessLasso if I recall (correct me if I'm wrong) don't run at the same privilege level and isn't able to modify the affinities etc.
> 
> You could setup a simple login script to use processhacker to make the changes then have the script also unload processhacker dll at the end once the change is made since it's detected as unwanted dll by some anti-cheats.

Thank you very much. I will learn how to do that.

**Comment by amitxv** [comment]
That is expected because the process is ``PsProtectedSignerWinTcb-Light`` protected. It is unprotected on Windows 7 for reference

**Comment by dougg0k** [comment]
Any idea how to bypass/disable the protection?

**Comment by amitxv** [comment]
Process Hacker to bypass and set as mentioned above or [katlogic/WindowsD](https://github.com/katlogic/WindowsD) to remove the protection. Beware of anticheat complaints.

**Comment by dougg0k** [comment]
I know about WindowsD, just didnt want to use. I meant in powershell if there were anything. 

Though I might take a look at SystemInformer/ProcessHacker, if there are commands to be used. It should only be a problem if it's open, for anticheats that is.
