### ISSUE TITLE
persistently disabling interrput moderation on xHCI disabling technique?

### ISSUE THREAD

**Issue by dragoon231** [djdallmann/GamingPCSetup#12]
Hey DJDallmann,

is it possible to autorun a batfile like mentioned in this step? i dont have much experience in coding and such i've done your method and it works for me. but on this other optimization guide,

https://github.com/BoringBoredom/PC-Optimization-Hub/blob/main/content/xhci%20imod/xhci%20imod.md

he mentions a different technique.

is this different? because when trying his method i don't seem to be able to see the "changes" when moving the mouse around. he doesn't have a way directly to contact him so I was wondering if you can help me here.

**Comment by djdallmann** [comment]
Yea his method works using **RWEverything** in bat file, you just need to know the right ADDRESS to modify.

**Comment by dougg0k** [comment]
I built an automated script for this, but I am unable to test since I am on win11 22h2 and rw is not working.

https://github.com/dougg0k/gaming_os_tweaker/blob/main/scripts/optional_helpers/interrupt_moderation_usb.ps1

Any way to confirm that the implementation is correct? 

I am also looking for information about AMD Controllers, if it's the same way as intel or works differently.

https://github.com/dougg0k/gaming_os_tweaker/issues/12

**Comment by BoringBoredom** [comment]
>i don't seem to be able to see the "changes" when moving the mouse around

Try checking the next page. It's not always on the first one.

>Any way to confirm that the implementation is correct?

It won't always be @ 2024. You'll need to figure out the exact location automatically.

>I am also looking for information about AMD Controllers

I don't own an AMD system, so I can't help you with that.

**Comment by dougg0k** [comment]
Right, that's what I wanted to know, is there any pattern or way you might know to find that exact location?

What is that exact location anyways?

**Comment by dougg0k** [comment]
Nevermind, I was able to resolve the issue for Intel, if anyone care to test.

**Comment by dougg0k** [comment]
Nevermind, I was able to resolve the issue for Intel, if anyone care to test.

https://github.com/dougg0k/gaming_os_tweaker/blob/main/scripts/optional_helpers/interrupt_moderation_usb.ps1

I still dont have any information for AMD.

---

Edit:

Even then, the docs are confusing, it doesnt feels that the script are 100%, I would need someone who understand to test and maybe help correct what is not correct.

@BoringBoredom @djdallmann

**Comment by BoringBoredom** [comment]
I updated [this page](https://github.com/BoringBoredom/PC-Optimization-Hub/blob/main/content/xhci%20imod/xhci%20imod.md) with a guide since the one in this repository is partially incorrect. `Runtime Register Space Offset` is 32 bits instead of 16 bits and located at +0x18 instead of +18 (the red number in RWE is a decimal, not hex). It was just a coincidence that both values were 0x2000 in that specific case.

**Comment by dougg0k** [comment]
Nice, ok, so, based on the updated guide

First step from rweverything seems feasible if the value, in the case of the screenshot (0x2000) will always stay at the first 32bit position.

Second step from the previous step value, add 0x24 and (32 * 0) to it. Does it mean that will always go to the proper value in the table? Should the total go stragith at the first value? 
Because it seems you selected the 128 position value, but you didnt add (32 * 0) to the starting address.

Did I misunderstood anything? @BoringBoredom

**Comment by dougg0k** [comment]
Right, but what I didnt understood yet is, in the last RW screenshot, you selected the 128 position with value 0x074B0FA0, is that the exact value of Runtime Base + 0x24 + (32 * 4 (or 0, doesnt matter)) or it's a position you had to go looking for manually?

@BoringBoredom

**Comment by BoringBoredom** [comment]
![image](https://github.com/djdallmann/GamingPCSetup/assets/16615327/5efd5234-2284-46cb-aab5-e24057fdffea)

**Comment by dougg0k** [comment]
Wow, I see, in every interrupt, from the first position, it repeats itself every 2 lines, but the correct value will have the end value of the repeated value, but something different for the first 4 digits. If that is correct, then it's predictable.

So total of 2048 lines to be dumped and parsed through, to find the right interruptor and value in it.

You said that this 0FAO is what I want, but that is to find out the pattern, right? 

Still the 0x074B0FAO is the value/address I would use with RWEverything?

@BoringBoredom

**Comment by dougg0k** [comment]
After trying this out myself, the first value from * 0, kept changing even if I was not moving the mouse, I have the refresh interval very low, either way. 

```
0xFC300000 = 4231004160
00000000FC300018 - First position 0x000004C0 = 1216
4231004160 + 1216 = 4231005376 = 0xFC3004C0
4231005376 + (32 * 1) = 0xFC3004E0
```

I saw the 0FA0, but no predictable pattern like in your screenshot.

Another problem, it seem the left side of the memory range, comes as 8 digits hex, not 16 when fetching through powershell. But given what you had done, all 16 were used. Here they cut from the first non-zero value, I wonder if they do the same in your case.

If you could check in powershell: `Get-CimInstance -ClassName Win32_DeviceMemoryAddress`

![32times0](https://github.com/djdallmann/GamingPCSetup/assets/10801221/8e78f9ce-9e08-4171-a5f5-6180b70db983)
![32times1](https://github.com/djdallmann/GamingPCSetup/assets/10801221/437cf09f-df57-402f-887c-ac57010ee308)

**Comment by BoringBoredom** [comment]
Everything you need to know is explained in the screenshots of the xHCI documentation. Take your time to read and understand it, otherwise you won't understand what I was talking about in my earlier posts.

**Comment by dougg0k** [comment]
Sure, but what I have been trying to get is understand certain details and as to find a pattern that is predictable so it can be coded.

I see you updated the guide again, thanks, you said to test, change last 4 values of a 32bit value to FA00, but what would that result in? 
Afaik there is nothing to check against that other than visual, unless there is a way to get a result from that in code, it's still just manual and visual instruction.

Top left number, in your case, that seems like a array memory position value, what do you mean add to the address, what address? 
It's a bunch of unclear details, it's expecting you to know a bunch before, and not giving details as if I you know nothing.

**Comment by dougg0k** [comment]
I implement the part I told I would, what remains now is find a pattern that is codeable to find the address, given all the interruptors 32bit values, if that is even possible.

https://github.com/dougg0k/gaming_os_tweaker/blob/main/scripts/optional_helpers/interrupt_moderation_usb.ps1

Anyone whom might be interested, feel free to review and maybe even finish and implement what remains.

@BoringBoredom @amitxv

**Comment by dougg0k** [comment]
What parts are overly complicated?

Current solution is only built given updated instructions from BoringBoredom.

**Comment by amitxv** [comment]
Regarding my question, I was wondering as to how you are reading addresses. You can read addresses from CLI with:

```bat
.\RW.exe /Command="R32 <address>" /Stdout
```

For determining the amount of interrupters, I think you can count the amount of IRQs the device is using but i'm not totally sure so don't quote me on that. Everything is the same for AMD, I tested it on another system.

https://www.amd.com/system/files/TechDocs/51192_Bolton_FCH_RRG.pdf

**Comment by dougg0k** [comment]
Sure, you can, but the address could be anywhere in any position from in any interrupter. I then dumped all interrupters, parsed through, if there is a way to go through and compare them all to find the proper pattern as to identify the right address, then what I did would facilitate it.

Good to know about AMD, there are a bunch of other besides Intel and AMD, will use the same implementation for them all.

**Comment by dougg0k** [comment]
Do you think this tool could facilitate finding the right address? @BoringBoredom 

https://desowin.org/usbpcap/tour.html

**Comment by amitxv** [comment]
Apologies, I didn't see that you included the snippet in your script. 

Without determining the amount of interrupters, it is difficult to determine how many addresses to iterate over to disable IMOD for.

> Not if it's changing when mouse are moving (that is not possible to see data wise). Only visually and in realtime.

You could check whether the IMOD counter is > 0.

**Comment by dougg0k** [comment]
No problem. 

Given docs there are 1024 interrupters. So hence it will always iterate through them all, per controller.

But there are many left side values that are higher than 0, doesnt mean it's the actual correct address / position.

**Comment by amitxv** [comment]
The docs mention that there can be *up to* 1024 interrupters, meaning there may not be 1024. I haven't looked into this that much but I don't think assuming there are always a fixed amount of interrupters is a good idea because you may be spilling into another address space in case that the space is dynamic. If it is fixed then I guess it is fine but as I said, haven't looked into it that much.

> The Interrupter logic consists of an Interrupter Management Register, an Interrupter Moderation Register, and the Event Ring Registers. A one to one mapping is defined for Interrupter to MSI-X vector. Up to 1024 Interrupters are supported.

On the other hand, the AMD docs mention that there can be *up to* 8 interrupters. You can't really continue without determining the amount of interrupters to disable IMOD for.

**Comment by BoringBoredom** [comment]
> First interrupter has 7 32-bit positions, while every other after, have 8

They're all 8x4 bytes.

> the address could be anywhere in any position from / in any interrupter

The IMOD register is always in the same spot within an interrupter: `Runtime Base + 0x24 + (32 * interrupter index)`

![image](https://github.com/djdallmann/GamingPCSetup/assets/16615327/65ad6a30-e56c-440e-91be-f2a27454b2b0)
![image](https://github.com/djdallmann/GamingPCSetup/assets/16615327/95a0fbf2-bf5f-4045-aa5d-e8218af57e98)

**Comment by dougg0k** [comment]
It's done, if anyone care to review and test if it's disabling the right addresses.

https://github.com/dougg0k/gaming_os_tweaker/blob/main/scripts/optional_helpers/interrupt_moderation_usb.ps1

What remains would be to have a way to identify the actual amount of interrupters.

**Comment by amitxv** [comment]
As mentioned before, you can't assume that there will be a fixed amount of interrupters. For example, there is nothing at interrupter 1023 on my system. I wouldn't be comfortable with a script modifying random addresses.

![image](https://github.com/djdallmann/GamingPCSetup/assets/86924251/bd158829-ebbe-4322-8183-1b635963b753)

**Comment by dougg0k** [comment]
I understand, If you read my comment above

> What remains would be to have a way to identify the actual amount of interrupters.

If you or someone else are able to provide an way to identify the correct address and not apply disable through them all or provide a way to identify the correct amount of interrupters in a device, that would solve the problem.

**Comment by dougg0k** [comment]
Found a way to get interrupters count, but only through windbg. https://learn.microsoft.com/pt-br/windows-hardware/drivers/debugger/-usb3kd-xhci-capability

Interrupt interval directly linked to usb bus?! https://docs.rs/usb-device/latest/usb_device/bus/trait.UsbBus.html

So 0XFA0 reset the interval, and there can be multiple instances of it if I didnt misunderstood.  https://docs.xilinx.com/r/en-US/am012-versal-register-reference/IMOD_0-USB2_XHCI-Register 

Bitrange 15:0 what does it mean? Here it says 8 registers https://edc.intel.com/content/www/us/en/design/publications/13th-generation-core-processor-datasheet-volume-2-of-2/interrupter-moderation-imod0-offset-2024/

PciInterruptCount - But in usb viewer it's always 1. So, might not be this one. https://learn.microsoft.com/en-us/windows/win32/api/usbuser/ns-usbuser-usb_bus_statistics_0

**Comment by amitxv** [comment]
What has this got to do with IMOD? https://github.com/dougg0k/gaming_os_tweaker/blob/2c6ed3295e2ed539d9c5b5aa7fdf9b0fa3186b3c/scripts/optional_helpers/interrupt_moderation_usb.ps1#L108-L114

On another note, nobody has been able to prove whether that does anything.

**Comment by dougg0k** [comment]
That is just meant to give irq priority to usb controlllers. An attempt to help increase responsiveness of mouse and keyboards. Though it could be more specifically set, I suppose, like to, only controllers that have mouse and keyboard plugged in. 

I might refactor that later to the interrupt affinity auto script instead.

**Comment by amitxv** [comment]
That doesn't contain information for those registry entries. They have been polluting the internet for a while and a lot of people seem to use them without real evidence that it has any effect so I was wondering whether someone finally had any. On the other hand, Windows Internals specifies that ``DevicePriority`` changes IRQ priorities which can I believe can be verified in WinDbg.

![image](https://github.com/djdallmann/GamingPCSetup/assets/86924251/d011b949-a8e1-4804-9672-2edd24df1c86)

**Comment by dougg0k** [comment]
Yeah. Correct.

But from what I see they have different purposes, but both are able to affect devices. Where one is for IRQ (not only devices) and the DevicePriority are for devices only. 

---

I use DevicePriority in some choices I did in this other automated script.

https://github.com/dougg0k/gaming_os_tweaker/blob/main/scripts/optional_helpers/interrupt_affinity_auto.ps1

**Comment by amitxv** [comment]
> both are able to affect devices

Do you have any evidence or official documentation for the registry entries affecting anything? At least ``DevicePriority`` is officially documented. As far as i'm concerned, those ``IRQXPriority`` entries are made up until anyone proves otherwise.

> Where one is for IRQ (not only devices) and the DevicePriority are for devices only.

Windows Internals mention that it controls IRQ priorities per-device though.

> I guess it somewhat make sense to be in this script too

I completely disagree. I wouldn't expect a script that was intended to disable xHCI interrupt moderation to mess with IRQ priorities. The topics are completely unrelated.

> if the changes only are microseconds, most would probably not be able to truly do

I'm not talking about benchmarks, I mean whether the setting has any feedback within the OS (e.g. WinDbg). Benchmarking introduces variables which may lead to invalid conclusions in the scenario where A vs. B made a difference in scores while the registry entry does not even exist.

**Comment by dougg0k** [comment]
No, no evidence. Many tweaks might have minor or no affect. 

In these cases, if it's there and does nothing, doesnt really matter. Since it shouldnt affect anything. It's not about the bad dissemination that happens on the internet with big videos about it. I just include tweaks that might have a potential positive effect in certain cases, if in total there is positive results, good, if not, doesnt matter.

Since I have no means to verify. If at some point it's verified by someone, it can just be removed.

**Comment by amitxv** [comment]
Some *tweaks* have negative effects too. Without understanding or justifying the change, it wouldn't be appropriate to apply it to a system in my opinion. It is not that big of a deal with a non-existent registry key but helps to prevent spreading false information around the internet. With this mindset, nobody will keep track of what is making a system perform worse or better.

**Comment by dougg0k** [comment]
For sure. I told my justification on it above, I can just remove it, though the script are still lacking in the parts to identify the amount of interrupters or the right address.

Here in answer that goes to your point. https://superuser.com/a/1393759

**Comment by dougg0k** [comment]
I removed the IRQ tweak from the script, however I will use in the other affinity script for the controller of the mouse and keyboard. 

I also added comments above the script to better give directions to anyone that might want and are able to help, with the remaining issues to be able to finish the script.

**Comment by amitxv** [comment]
The Intel docs demonstrate how the amount of interrupters can be determined. You can also refer to BoringBoredom's updated page. The bits 18:8 align with  ``!usb3kd.xhci_capability`` in WinDbg.

![image](https://github.com/djdallmann/GamingPCSetup/assets/86924251/45852487-e70a-46c2-9012-a304abec5846)

**Comment by dougg0k** [comment]
Oh, didnt see that he had updated the guide again.

**Comment by amitxv** [comment]
Well, the info was in the Intel docs to begin with. It also seems consistent with other vendors.

**Comment by dougg0k** [comment]
Cool. It's done.

https://github.com/dougg0k/gaming_os_tweaker/blob/main/scripts/optional_helpers/interrupt_affinity_auto.ps1

---

Pretty much the only thing left is to verify this, in different OSs. If it's grabbing the interrupters addresses correctly.

For Win7 and Win10 there are different values to differentiate between what is a correct IMOD address, I need to know that the script are currently grabbing the correct address given your OS. I dont know the values for Win11, if they are like Win10 or not. So for now, only matters Win7 and Win10, unless you have deep knowledge of the subject and know about Win11, let us know. 

It's to verify if the implementation are correct / accurate.

Reference: https://www.overclock.net/threads/usb-polling-precision.1550666/page-61#post-28580928

**Comment by amitxv** [comment]
> Pretty much the only thing left is to verify in different OSs. If it's grabbing the interrupters addresses correctly. To know if the implementation are correct / accurate.

The address will always be correct assuming you have the correct offsets and that they are consistent across vendors.

> I am on Win11 22h2 with the new high pooling rate fixes. Not sure if the changes reached imod though.

The updated input stack is unrelated to xHCI interrupt moderation. [It limits the raw input listening rate for background processes](https://twitter.com/amitxv/status/1666157717759877120).

**Comment by dougg0k** [comment]
Is this worth doing? 
https://www.overclock.net/threads/usb-polling-precision.1550666/page-61#post-28582024 EHCI / Interrupt Threshold Control

Only for background processes? Because apparently, there were improvements for high hz mouse.

**Comment by ApaDoctor** [comment]
Hello :) 
I see that the automated script gist is deleted, does anybody still have it? 🙏 
Huge thanks in advance

**Comment by OWENPCSERVICE** [comment]
Hey dragon how did you find the path to rweverything?
