### ISSUE TITLE
HDCP Citation needed

### ISSUE THREAD

**Issue by Sythys** [djdallmann/GamingPCSetup#14]
"To note I'm not the original pioneer of this finding, just helped to simplify it through testing." Can you please provide your source? I need to disable HDCP on just one monitor. I got difficulties finding a solution for this.

master/CONTENT/RESEARCH/WINDRIVERS -> hdcp

**Comment by djdallmann** [comment]
I don't have good news... although I wasn't the original person who lead me to this registry key/value but there is no official documentation/source of how the registry key(s) work. Some findings are through reverse engineering, code analysis or sometimes through trial and error.

**Comment by Sythys** [comment]
Ok, thank you. Have you found this flag yourself?

**Comment by HackerPide** [comment]
@Sythys if u have an Nvidia GPU, it seems you have to use an AMD GPU with it. Nvidia has a [registry option](https://www.techpowerup.com/forums/threads/feature-suggestion-disable-hdcp.283141/) to disable HDCP globally while on AMD you can set it per display.
