### ISSUE TITLE
maybe you know this?

### ISSUE THREAD

**Issue by tigros** [djdallmann/GamingPCSetup#18]
Hi,

Did you ever notice that on Windows 7 certain file types are automatically set to critical I/O priority when reading them, like mp3, mp4 etc? I don't think it matters what application is doing the reading.

I would like this to happen on Windows 10/11, any ideas?

Also i'd like to add file types on windows 7 like .flac, how to do that? 

An answer to this would be helpful to tons of ppl i'm sure! nobody likes listening to a broken record.

Thanks!

**Comment by djdallmann** [comment]
Can you share your methods or process regarding certain filetypes automatically use X I/O priority? Are you opening the audio files with specific software, which software, what version? What are you using to check, process hacker?

**Comment by tigros** [comment]
any software as long as it's reading .mp3, .mp4, .avi probably others, yes process hacker disk tab, filter on .mp3 etc.

i don't know of any special software i've installed that does this, but when i check the same in a virtual win 7 it doesn't happen, weird!

**Comment by djdallmann** [comment]
My first guess is Windows Multimedia Class Scheduler Service (MMCSS), here's a quick way to find out. Close your programs that's working on the audio files, go to services and disable the service. Then redo your test to see if IO priority is still being influence.

**Comment by tigros** [comment]
ok tried it, even rebooted for good measure, no change. it disables all audio anyway since it turns off "Windows Audio" service.

you can do a "copy big.mp3 bigcopy.mp3" and only the reading is in critical, bigcopy is Normal. so that proves it's not just a certain program.

really obscure, yet so useful!
