### ISSUE TITLE
Unable to use the DSC script, got error

### ISSUE THREAD

**Issue by dummys** [djdallmann/GamingPCSetup#21]
Hello,

I'm trying to test your script and unfortunately it didnt work as expected.
First of all i'm testing on a VMWare virtual machine.
I installed Windows 11 pro using `Win11_23H2_EnglishInternational_x64v2.iso` downloaded from microsoft today.
I do the full windows update and rebooted, then I tried following your explanation.
After the second time running the `Start-DscConfiguration -Path .\GamingMinimal\ -wait -verbose` I get this error:
```
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer DESKTOP-F6VNTVA with user sid S-1-5-21-3581580102-3493083843-3643019517-1001.
VERBOSE: [DESKTOP-F6VNTVA]: LCM:  [ Start  Set      ]
VERBOSE: [DESKTOP-F6VNTVA]: LCM:  [ End    Set      ]
A configuration is pending. If you are in Pull mode, please run Update-DscConfiguration to pull a new configuration and apply it. If you are in Push mode, please run Start-DscConfiguration command with -Force parameter to apply a new
configuration or run Start-DscConfiguration command with -UseExisting parameter to finish the existing configuration.
    + CategoryInfo          : ResourceExists: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 11
    + PSComputerName        : localhost

VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 0.146 seconds
```

Then using the `Get-DscConfiguration` I got another error: 

```
WARNING: [DESKTOP-F6VNTVA]:                            [] The GET operation will be carried against a pending
configuration since the latest configuration has not converged yet.
Get-DscConfiguration : PowerShell DSC resource MSFT_ServiceResource  failed to execute Get-TargetResource
functionality with error message: Service 'TabletInputService' not found.
At line:1 char:1
+ Get-DscConfiguration
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (MSFT_DSCLocalConfigurationManager:root/Microsoft/...gurationManager)
   [Get-DscConfiguration], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure,Get-DscConfiguration
```
The service `TabletInputService` does not exist on my VM, but why it make everything not working ?

After rebooting the second time I tested the config: `Test-DscConfiguration`

```
Test-DscConfiguration
WARNING: [DESKTOP-F6VNTVA]:                            [] The TEST operation will be carried against a pending configuration since the latest configuration has not converged yet.
False
```
What seems to be wrong to me is this error: `since the latest configuration has not converged yet.`
Which means for me that something is wrong in the script. As I'm really not a expert of DSC (to be honest you make me learn it) I don't know how to help to debug further. Please advise. thanks.

**Comment by dummys** [comment]
Found something, if I delete both: 

https://github.com/djdallmann/GamingPCSetup/blob/2b9bd04bf9f7a83a3c12b9d979828d2ca6cbf8da/CONTENT/DOCS/PSDSC/GamingMinimal.ps1#L655

https://github.com/djdallmann/GamingPCSetup/blob/2b9bd04bf9f7a83a3c12b9d979828d2ca6cbf8da/CONTENT/DOCS/PSDSC/GamingMinimal.ps1#L605

It works. In other word, if a service does not exist, then the script is making error and do not apply the config.

**Comment by djdallmann** [comment]
Thanks, this guide was last compatible for Win10 2004 and I haven't incorporated any Windows 11 changes yet. I've been using Windows 11 for a couple months now and accumulating a few new things that will likely end up on my github. I'll leave this feedback open for now until that happens.

**Comment by djdallmann** [comment]
Merged your pull request, thanks for your contribution.
