### ISSUE TITLE
Question regarding binding RSS queues

### ISSUE THREAD

**Issue by PrototypeGR** [djdallmann/GamingPCSetup#23]
Hello,

So the recommendation goes as following,

Recommendation: If you have a 4 core CPU, try binding RSS queues to cores 2 and 3 (3rd and 4th core)

If we have more than a 4 core CPU, for example a Ryzen 9 5900X, it should be set as Set-NetAdapterRSS -Name "Ethernet" -BaseProcessorNumber 2 again?

Thank you

**Comment by djdallmann** [comment]
Yes that should be fine, the main point was to move the affinity away from default cores, such as core0. Use xperf to determine if it had a positive impact.

**Comment by PrototypeGR** [comment]
Thank you for the reply. I will give it a try. Unfortunately i have a Realtek NIC but it's 2.5G that's the only reason i'm using it. I also have a Intel on my mobo but it's 1G although it's limiting a little bit my internet connection because i have fiber..
