### ISSUE TITLE
Smaller fps

### ISSUE THREAD

**Issue by AmeisWut** [djdallmann/GamingPCSetup#5]
After using powershell scripts my fps are lower. Do you have revert scripts? I dont want to reinstall windows.

**Comment by djdallmann** [comment]
Less fps in comparison to default windows install (no tweaks), or in comparison to other things you tried?   If I had to guess it could be GameMode being disabled that could have a difference in FPS if it's the powershell script.

These are all the settings changed by the Powershell script: https://github.com/djdallmann/GamingPCSetup/blob/master/CONTENT/DOCS/PSDSC/ConfigList.md.
