### ISSUE TITLE
Pc Gamer à 500€ !

### ISSUE THREAD

**Issue by WizGowGit** [djdallmann/GamingPCSetup#8]
Boitier : https://www.cdiscount.com/informatique/boitiers-pc-alimentations/aerocool-boitier-pc-cylon-mini-avec-fenetre-plei/f-10766-inn4718009152168.html?idOffre=332300189

Carte mère : https://www.cdiscount.com/informatique/cartes-meres/carte-mere-msi-a320m-a-pro-max/f-10765-msi4719072667665.html?idOffre=-1

Processeur : https://www.cdiscount.com/informatique/cartes-meres/carte-mere-msi-a320m-a-pro-max/f-10765-msi4719072667665.html?idOffre=-1

Ram : https://www.cdiscount.com/informatique/memoire-ram/hyperx-memoire-pc-ram-fury-ddr4-rgb-8go-1x8/f-10716-hyp0740617296327.html?idOffre=-1

Alimentation : https://www.cdiscount.com/informatique/composants-informatique/corsair-alimentation-pc-cv-series-cv-450-80-pl/f-10701-cp9020209eu.html?idOffre=-1

Carte Graphique	: https://www.cdiscount.com/informatique/cartes-graphiques/gigabyte-carte-graphique-gigabyte-geforce-gt-1030/f-10767-gig4719331301699.html?idOffre=190860844

Ventilateur : https://www.cdiscount.com/informatique/ventilation-refroidissement/3pcs-led-ventilateur-ordinateur-rgb-refroidisseur/f-10789-auc0705604628970.html?idOffre=552488367

Cable Sata : https://www.cdiscount.com/informatique/boitiers-pc-alimentations/corsair-cable-gaine-premium-sata-6gbps-noir-60cm-9/f-10766-cc8900282.html?idOffre=-1

**Comment by ArtanisInc** [comment]
C’est pas le bon endroit pour ce genre de chose mon reuf, mais why not 🤷
